### ISSUE TITLE
<Waiting> players don't get platform skipped

### ISSUE THREAD

**Issue by PetTurtle** [PetTurtle/Zero-Wars#10]

**Comment by Lasica** [comment]
Just ignore player number, spawn all thats on said platform no matter which player owns it.  Since units cant move there will be no more sheningans

**Comment by PetTurtle** [comment]
Need know what teams are on platforms so in the future when i remove nullAI I can tell who the give the cloned unit to without looping though each unit and checking their team

**Comment by PetTurtle** [comment]
should be fixed
