### ISSUE TITLE
With ducks added Core base dies way too easily

### ISSUE THREAD

**Issue by Lasica** [PetTurtle/Zero-Wars#22]
I suggest buffing hp to at least 20000. It's easy to be rushed with gnats as well as it has no riot capabilities.

I suggest giving it additional powerful weapon that unlocks at 200 + energy grid, add pylon behind airpads at start for both sides, increase pylon range to reach the weapon

**Comment by PetTurtle** [comment]
Ducks removed and hero do less dmg, also respawn faster (depending on level)
