### ISSUE TITLE
Early game snowballing is a problem, lategame exp starvation as well

### ISSUE THREAD

**Issue by Lasica** [PetTurtle/Zero-Wars#23]
Make duck cost changing with each level 200 -> 450-> lvl(x) = lvl(x-1) + 250*(x-1)

lvl
1 | 200
2 | 450
3 | 950
4 | 1700
5 | 2700
6 | 3950
7 | 5450
8 | 7200
9 | 9200
10 | 11450
11 | 13950
12 | 16700
13 | 19700
14 | 22950
15 | 26450
16 | 30200
17 | 34200

**Comment by PetTurtle** [comment]
Higher Level Heroes have longer respawn time, and get less xp for killing lower level heroes
