### ISSUE TITLE
Make medium factory more attractive, Heavy less attractive

### ISSUE THREAD

**Issue by Lasica** [PetTurtle/Zero-Wars#26]
Base: remove Thug, add Hermit
Medium lvl 1: remove Bandit, Redback, Archer, Rogue, Vandal
Medium lvl 1: add Bolas, Ripper,  Recluse, Angler
Medium lvl 2: add Firewalker, Aspis, remove Minelayer, Racketeer
Heavy lvl 1: remove Ripper
Light lvl 1: remove Sling, Hermit
Light lvl 1: add Rogue, Thug

It may be a bit too many good units in medium, maybe Firewalker belongs to adv light instead. I wanted to make Recluse adv tier but I don't have any idea which other skirm could fit in Medium lvl 1, game lacks of skirmishers a bit.

I'd like to add funnelweb too, so as a separate suggestion I'd move Crabe -> light lvl 2, add Funnelweb to Specialist lvl 2.

**Comment by Lasica** [comment]
Possibly also move Grebe tier 2 -> tier 1, replacing Scythe

**Comment by Lasica** [comment]
Possibly move Catapult from adv Medium to adv Heavy if accepting above changes, as there will be plenty artillery in medium category.

**Comment by PetTurtle** [comment]
tried fire walker and its kinda op

**Comment by PetTurtle** [comment]
I like all this, but removing fire walker, 8 of them can counter entire wave alone
