### ISSUE TITLE
v1.54 feedback

### ISSUE THREAD

**Issue by Lasica** [PetTurtle/Zero-Wars#36]
Racketeer in tier 1 was probably not a good idea given how good it is in disabling starlight and enemy ducks. Need more testing though

Recluse proves strong, probably tier 2 strong, but I think that's ok for now to 

Fix starting with 0 metal

Chickens need more rebalancing and love, dodos seem  to deal 0 dmg. Not sure that u added blimpy tweaks, probably needs more tweaking. Fixing dodo may be enough.

Shields probably need energy cost reduced by 10 fold or something.

Disable chicken shields linking.

Anti air seems to still be stacking a lot, look for bug in my code...

**Comment by Lasica** [comment]
Tiamat probably a bit too good for cost.

**Comment by PetTurtle** [comment]
Fixed everything But shields, however chicken shields are smaller, and have the regen as thug
