### ISSUE TITLE
Hero Sniper has speed reset when disarmed

### ISSUE THREAD

**Issue by GoogleFrog** [PetTurtle/Zero-Wars#55]
A hero sniper with speed upgrades permanently reverts to slow speed when disarmed. I suspect that somewhere in Zero Wars the speed of units is being changed directly, rather than using the attributes framework.

You can use self move speed change, as seen in Krow.

**Comment by GoogleFrog** [comment]
Here is your problem: https://github.com/UndoBlaze/Zero-Wars/blob/master/ZeroWars.sdd/LuaRules/Configs/Hero_Unit_Defs.lua#L506

"maxSpeed" should never be used in Spring.MoveCtrl.SetGroundMoveTypeData outside the attributes gadget.

For that matter, "reloadTime" should never be set in Spring.SetUnitWeaponState.

**Comment by PetTurtle** [comment]
how would I change "reloadTime"?

**Comment by GoogleFrog** [comment]
For now you can use selfReloadSpeedChange. Look in the attributes gadget.
