### ISSUE TITLE
Hero puppy is half invulnerable in jump

### ISSUE THREAD

**Issue by Feugent** [PetTurtle/Zero-Wars#68]
While jumping hero Puppy does not take any damage which is seen on the health bar.
But in reality Puppy does take damage, which is seen by respawning after the respawn time runs out.
Puppy does not go to the respawn platform in this time and can still attack and kill other heroes.
This is especially weird with high burst dmg heroes like the new moderator hero which could 1hit Puppy on lvl 2 but gets killed just barely before puppy respawns.

**Comment by PetTurtle** [comment]
This could be fixed, see if it happens in v2

**Comment by Feugent** [comment]
seems fixed
