### ISSUE TITLE
Placing your builder very close to the right side of the start boxes causes a small builder to spawn, resulting in your wave not spawning

### ISSUE THREAD

**Issue by Feugent** [PetTurtle/Zero-Wars#84]
e.g. Kaszkin http://zero-k.info/Battles/Detail/932139

**Comment by Feugent** [comment]
Placing your builder very close to the right side of the startbox (on both team sides) causes a small builder to spawn instead of a big one.
This causes your waves to not spawn at all.
The startboxes have to be smaller or the checkbox for the builder have to be bigger to stop this from happening.

**Comment by StuffPhotonDev** [comment]
Could prehaps making the startbox smaller slove the issue by preventing players from starting in the problematic parts?

**Comment by PetTurtle** [comment]
fixed
