### ISSUE TITLE
Constant m/s and e/s additions are per team and not per player

### ISSUE THREAD

**Issue by Feugent** [PetTurtle/Zero-Wars#89]
https://github.com/PetTurtle/Zero-Wars/blob/a6411ff64bbc338ca151a0bbba44faa9d7751855/ZeroWars.sdd/luarules/gadgets/zerowars/side.lua#L20

this does only apply per team idk if this is intentional but it seems to confuse players to get different metalincome per playercount.

E.g. 1v1 both have 5m/s and 0e/s
3v3 players have 3m/s and 1.333e/s
(+2/+2 from per player from Zero-k side and the other value is split between players)

**Comment by PetTurtle** [comment]
metal income changed to flow based mex income fixing this problem
